name: Docs workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Specific Node.js version 🦄
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 📎
        run: |
          npm install
          npm run docs:build

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
